---
- hosts: all
  become: yes
  pre_tasks:
    - name: "include x86_64 config"
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
      when: ansible_architecture == "x86_64"
  tasks:
  - apt:
      update_cache: yes
  - import_role:
      name: geerlingguy.github-users
    tags: [users]
  - import_role:
      name: geerlingguy.security
    tags: [security]
  - import_role:
      name: geerlingguy.docker
    tags: [docker]
